name = "ExtensionsExt"
uuid = "10b1be5d-af5e-4ede-8ee2-c593888d75f3"
authors = ["longemen3000 <longemen3000@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
